version: '3.7'

services:

  # application container
  node:
    container_name: node-backend
    image: nodedocker
    restart: on-failure
    command: "npm run start:pm2-dev"
    build:
        context: ./
        dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/html/
      - /var/www/html/node_modules
      - ./logs:/var/www/html/logs
    ports:
      - 8000:3000
    depends_on: 
      - mongo
    networks:
      - nest_network

  # mongodb container 
  # mongo:
  #   container_name: node-database
  #   image: mongo:7.0.0-rc8-jammy
  #   restart: on-failure
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - "./storage/db-data:/data/db"
  #   networks:
  #     - nest_network
      
#network to hold backend/nginx/mongo
networks:
  nest_network:
    driver: bridge