services:
  # application container
  node:
    container_name: nestjs-base-project
    image: nodedocker
    restart: on-failure
    command: "npm run start:pm2-dev"
    build:
        context: ./
        dockerfile: ./docker/DockerfileDev
    volumes:
      - ./:/var/www/html/
      - /var/www/html/node_modules
    ports:
      - 3000:3000
    networks:
      - nest_network

#network
networks:
  nest_network:
    driver: bridge